language: java
sudo: required
jdk:
  - oraclejdk8
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
  - jdk_switcher use oraclejdk8
  - mvn install
  - mvn cobertura:cobertura
before_install:
  - sudo apt-get install binutils
after_success:
  - bash <(curl -s https://codecov.io/bash)