/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EntityUnitCollection */

#ifndef _Included_io_github_shadowcreative_eunit_EntityUnitCollection
#define _Included_io_github_shadowcreative_eunit_EntityUnitCollection
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     io_github_shadowcreative_eunit_EntityUnitCollection
	* Method:    onChangeHandler0
	* Signature: (Ljava/lang/string;)Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_io_github_shadowcreative_eunit_EntityUnitCollection_onChangeHandler0
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif